# Generated by Django 4.2.2 on 2023-06-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxcom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='likes',
            new_name='love',
        ),
    ]
