# Generated by Django 4.2.2 on 2023-06-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxcom', '0002_rename_likes_product_love'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='love',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='like',
            name='product',
        ),
        migrations.AddField(
            model_name='like',
            name='like_product',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='maxcom.product'),
            preserve_default=False,
        ),
    ]
